

import { getServerSession } from "next-auth";
import authOptions from "@/app/(routes)/api/auth/[...nextauth]/options";
import Navbar from "@/app/_components/layout/navbar";
import "@mantine/core/styles.css";



type Link = {
  name: string;
  key: number;
};

type LinkGroup = {
  group: string;
  links: Link[];
};

type LinkData = LinkGroup | Link;

export const metadata = {
  title: "Join It",
  description: "Generated by Next.js",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  const linksData: Link[] | LinkData[] = [
    {
      group: "Aid",
      links: [
        { name: "Requests", key: 1 },
        { name: "Resources", key: 2 },
      ],
    },

    {
      group: "Community",
      links: [
        { name: "Comms", key: 4 },
        { name: "Events", key: 5 },
        { name: "Jobs", key: 6 }, // Make a community based job board for freelance workers
        { name: "Bookshelf", key: 7 },
      ],
    },

    {
      // TODO: Fix navbar width
      group: "Site",
      links: [
        { name: "About", key: 7 },
        { name: "Changelog", key: 8 },
      ],
    },
  ];

  if (session) linksData.push({ name: "Profile", key: 9 });

  return (
    <>
          <Navbar session={session} linksData={linksData} />
          {children}
          
    </>
  );
}
