import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import styles from '@/app/_styles/layout/layout.module.scss';
import { getServerSession } from 'next-auth';
import authOptions from '@/app/api/auth/[...nextauth]/options';
import Navbar from '@/app/_components/layout/navbar';
import '@mantine/core/styles.css';
import './globals.scss';

type Link = {
	name: string;
	key: number;
};

type LinkGroup = {
	group: string;
	links: Link[];
};

type LinkData = LinkGroup | Link;

export const metadata = {
	title: 'Join It',
	description: 'Generated by Next.js',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerSession(authOptions);

	const linksData: Link[] | LinkData[] = [
		{
			group: 'Aid',
			links: [
				{ name: 'Requests', key: 1 },
				{ name: 'Resources', key: 2 },
			],
		},

		{
			group: 'Community',
			links: [
				{ name: 'Communications', key: 3 },
				{ name: 'Events', key: 4 },
				{ name: 'Jobs', key: 5 }, // Make a community based job board for freelance workers
				{ name: 'Bookshelf', key: 6 },
			],
		},

		{
      // TODO: Fix navbar width
			group: 'Site',
			links: [
				{ name: 'About', key: 7 },
				{ name: 'Changelog', key: 8 },
			],
		},
	];

	if (session) linksData.push({ name: 'Profile', key: 9 });

	return (
		<html lang='en'>
			<head>
				<ColorSchemeScript />
			</head>

			<body>
				<MantineProvider>
					<Navbar
						session={session}
						linksData={linksData}
					/>

					<section className={styles.content}>
						<div className={styles.wrapper}>{children}</div>
					</section>
				</MantineProvider>
			</body>
		</html>
	);
}
