
import { MantineProvider, ColorSchemeScript } from "@mantine/core"
import styles from "@/app/_styles/layout/layout.module.scss"
import { getServerSession } from 'next-auth';
import authOptions from '@/app/api/auth/[...nextauth]/options';
import Navbar from '@/app/_components/layout/navbar';
import '@mantine/core/styles.css';
import './globals.scss'


type Link = {
  name: string,
  key: number
}



export const metadata = {
  title: 'Join It',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)

  const links: Link[] = [
    { name: "Requests", key: 1 },
    { name: "Resources", key: 2 },
    { name: "Groups", key: 3 }
  ]
  return (
    <html lang="en">

      <head>
        <ColorSchemeScript />
      </head>

      <body>

        <MantineProvider>

          <Navbar
            session={session}
            links={links}
          />

          <section className={styles.content}>
            <div className={styles.wrapper}>
              {children}
            </div>
          </section>

        </MantineProvider>

      </body>
    </html>
  )
}
