
import { Provider } from "./components/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}) {
  
  return (
    <html lang="en">
      <body>
      <Provider>
          {children}
      </Provider>
      </body>

    </html>
  )
}
