
import { Provider } from "./components/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}) {
  
  return (
    <html lang="en">
      <Provider>
          <body>{children}</body>
      </Provider>

    </html>
  )
}
